/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as SeriesSlugRouteImport } from './routes/series.$slug'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin._authenticated.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TitlesKindSlugRouteImport } from './routes/titles.$kind.$slug'
import { Route as AdminAuthenticatedContentIndexRouteImport } from './routes/admin._authenticated.content.index'
import { Route as AdminAuthenticatedContentNewRouteImport } from './routes/admin._authenticated.content.new'
import { Route as AdminAuthenticatedVideosIdPreviewRouteImport } from './routes/admin._authenticated.videos.$id.preview'
import { Route as AdminAuthenticatedContentTypeIdIndexRouteImport } from './routes/admin._authenticated.content.$type.$id.index'
import { Route as AdminAuthenticatedContentTypeIdEditRouteImport } from './routes/admin._authenticated.content.$type.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/series/$slug',
  path: '/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TitlesKindSlugRoute = TitlesKindSlugRouteImport.update({
  id: '/titles/$kind/$slug',
  path: '/titles/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedContentIndexRoute =
  AdminAuthenticatedContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedContentNewRoute =
  AdminAuthenticatedContentNewRouteImport.update({
    id: '/content/new',
    path: '/content/new',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedVideosIdPreviewRoute =
  AdminAuthenticatedVideosIdPreviewRouteImport.update({
    id: '/videos/$id/preview',
    path: '/videos/$id/preview',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedContentTypeIdIndexRoute =
  AdminAuthenticatedContentTypeIdIndexRouteImport.update({
    id: '/content/$type/$id/',
    path: '/content/$type/$id/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedContentTypeIdEditRoute =
  AdminAuthenticatedContentTypeIdEditRouteImport.update({
    id: '/content/$type/$id/edit',
    path: '/content/$type/$id/edit',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/titles/$kind/$slug': typeof TitlesKindSlugRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/content/new': typeof AdminAuthenticatedContentNewRoute
  '/admin/content/': typeof AdminAuthenticatedContentIndexRoute
  '/admin/videos/$id/preview': typeof AdminAuthenticatedVideosIdPreviewRoute
  '/admin/content/$type/$id/edit': typeof AdminAuthenticatedContentTypeIdEditRoute
  '/admin/content/$type/$id/': typeof AdminAuthenticatedContentTypeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/titles/$kind/$slug': typeof TitlesKindSlugRoute
  '/admin/content/new': typeof AdminAuthenticatedContentNewRoute
  '/admin/content': typeof AdminAuthenticatedContentIndexRoute
  '/admin/videos/$id/preview': typeof AdminAuthenticatedVideosIdPreviewRoute
  '/admin/content/$type/$id/edit': typeof AdminAuthenticatedContentTypeIdEditRoute
  '/admin/content/$type/$id': typeof AdminAuthenticatedContentTypeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/series/$slug': typeof SeriesSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/titles/$kind/$slug': typeof TitlesKindSlugRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/content/new': typeof AdminAuthenticatedContentNewRoute
  '/admin/_authenticated/content/': typeof AdminAuthenticatedContentIndexRoute
  '/admin/_authenticated/videos/$id/preview': typeof AdminAuthenticatedVideosIdPreviewRoute
  '/admin/_authenticated/content/$type/$id/edit': typeof AdminAuthenticatedContentTypeIdEditRoute
  '/admin/_authenticated/content/$type/$id/': typeof AdminAuthenticatedContentTypeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/api/$'
    | '/series/$slug'
    | '/watch/$slug'
    | '/api/auth/$'
    | '/titles/$kind/$slug'
    | '/admin/'
    | '/admin/content/new'
    | '/admin/content/'
    | '/admin/videos/$id/preview'
    | '/admin/content/$type/$id/edit'
    | '/admin/content/$type/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/api/$'
    | '/series/$slug'
    | '/watch/$slug'
    | '/api/auth/$'
    | '/titles/$kind/$slug'
    | '/admin/content/new'
    | '/admin/content'
    | '/admin/videos/$id/preview'
    | '/admin/content/$type/$id/edit'
    | '/admin/content/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/api/$'
    | '/series/$slug'
    | '/watch/$slug'
    | '/api/auth/$'
    | '/titles/$kind/$slug'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/content/new'
    | '/admin/_authenticated/content/'
    | '/admin/_authenticated/videos/$id/preview'
    | '/admin/_authenticated/content/$type/$id/edit'
    | '/admin/_authenticated/content/$type/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  SeriesSlugRoute: typeof SeriesSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TitlesKindSlugRoute: typeof TitlesKindSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug': {
      id: '/series/$slug'
      path: '/series/$slug'
      fullPath: '/series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titles/$kind/$slug': {
      id: '/titles/$kind/$slug'
      path: '/titles/$kind/$slug'
      fullPath: '/titles/$kind/$slug'
      preLoaderRoute: typeof TitlesKindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/content/': {
      id: '/admin/_authenticated/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminAuthenticatedContentIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/content/new': {
      id: '/admin/_authenticated/content/new'
      path: '/content/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminAuthenticatedContentNewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/videos/$id/preview': {
      id: '/admin/_authenticated/videos/$id/preview'
      path: '/videos/$id/preview'
      fullPath: '/admin/videos/$id/preview'
      preLoaderRoute: typeof AdminAuthenticatedVideosIdPreviewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/content/$type/$id/': {
      id: '/admin/_authenticated/content/$type/$id/'
      path: '/content/$type/$id'
      fullPath: '/admin/content/$type/$id/'
      preLoaderRoute: typeof AdminAuthenticatedContentTypeIdIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/content/$type/$id/edit': {
      id: '/admin/_authenticated/content/$type/$id/edit'
      path: '/content/$type/$id/edit'
      fullPath: '/admin/content/$type/$id/edit'
      preLoaderRoute: typeof AdminAuthenticatedContentTypeIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
  AdminAuthenticatedContentNewRoute: typeof AdminAuthenticatedContentNewRoute
  AdminAuthenticatedContentIndexRoute: typeof AdminAuthenticatedContentIndexRoute
  AdminAuthenticatedVideosIdPreviewRoute: typeof AdminAuthenticatedVideosIdPreviewRoute
  AdminAuthenticatedContentTypeIdEditRoute: typeof AdminAuthenticatedContentTypeIdEditRoute
  AdminAuthenticatedContentTypeIdIndexRoute: typeof AdminAuthenticatedContentTypeIdIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
  AdminAuthenticatedContentNewRoute: AdminAuthenticatedContentNewRoute,
  AdminAuthenticatedContentIndexRoute: AdminAuthenticatedContentIndexRoute,
  AdminAuthenticatedVideosIdPreviewRoute:
    AdminAuthenticatedVideosIdPreviewRoute,
  AdminAuthenticatedContentTypeIdEditRoute:
    AdminAuthenticatedContentTypeIdEditRoute,
  AdminAuthenticatedContentTypeIdIndexRoute:
    AdminAuthenticatedContentTypeIdIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  SeriesSlugRoute: SeriesSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TitlesKindSlugRoute: TitlesKindSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
